SELECT
  id,
  payer_name,
  city,
  amount_covered,
  amount_uncovered,
  revenue,
  covered_encounters,
  uncovered_encounters,
  covered_medications,
  uncovered_medications,
  covered_procedures,
  uncovered_procedures,
  covered_immunizations,
  uncovered_immunizations,
  unique_customers,
  avg_qols,
  member_months
FROM {{ ref('s_payers') }}